### ISSUE TITLE
Общие недочеты

### ISSUE THREAD

**Issue by mglknFSD** [igor-smolkov/my-jquery-slider#4]
Слайдер сделан очень круто, но демо страница не совсем то что ожидается. У демо страницы очень запутанный и перегруженый интерфейс.

Ожидается что ты сделаешь что-то вроде такого.

![g](https://user-images.githubusercontent.com/75975369/146673526-633d7eb7-9eff-44e5-8f45-2c1e7e22c994.png)
 
т е справа расположен сам слайдер, слева "ручки" для него, которые должны включать

- иипуты для максимального и минимальнго значения
- инпуты для текущий положений значений слайдера
- чекбокс для вертикального/горизонтального режимов
- чекбокс для шкалы
- чекбокс для тултипов (это цифра с значением над текущей позицией)
- чекбокс для прогрессбара (выделенная область между ползунками, если их больше одного, или между минимальным значением и ползунком если он один)

Больше ничего не надо.

И таких блоков 3 или больше.

Тут задача сделать именно слайдер (как библиотеку), простой но надежный. И задача демо страницы это показать. Ну и что бы у нас была возможность потестировать это на предмет багов.

**Comment by igor-smolkov** [comment]
на первой панели есть ссылка на упрощенную демо-страницу

![Скриншот 19-12-2021 205819](https://user-images.githubusercontent.com/56838535/146677940-2a12bf3d-4603-4736-9855-c2b110a833a2.jpg)

она сделана аналогично той, что есть в примере в задании
и по сути такая, как ты предлагаешь, только панель не слева от слайдера, а под ним

![Скриншот 19-12-2021 205910](https://user-images.githubusercontent.com/56838535/146677955-5993d083-a887-4548-b1e0-c8021d557c78.jpg)

могу изменить ее как на рисунке и поставить как основную демо-страницу

**Comment by mglknFSD** [comment]
> могу изменить ее как на рисунке и поставить как основную демо-страницу

Не, не надо, это то что нужно.

**Comment by mglknFSD** [comment]
Небольшой баг. При попытке назначить `from` больше чем `to` range пропадает.

https://user-images.githubusercontent.com/75975369/147380880-b8918af9-85bb-47b3-8b97-664d5dc5d7f1.mp4

**Comment by mglknFSD** [comment]
Странное поведение. При попытке назначить не валидное значение для минимального значения он сначала возвращает предыдущее минимальное значение, а потом меняется на какое-то другое. Этот баг у меня перестал воспроизводится, сейчас просто меняется значение.

https://user-images.githubusercontent.com/75975369/147381859-75f87210-1635-4359-95c9-3df41036c1dc.mp4

Тут поинт в том, что я не хотел то значение которое мне предлагает эвристика слайдера. Понятно что то значение которое я вводил не валидно, но логичным, с точки знения UX, как мне кажется, тут выглядит вернуть предыдущее значение и показать ошибку (последнее, наверное не обязательно - не будем усложнять)

И еще один момент, после любого изменения пределов, меняются и значения ползунков слайдера, даже если они не аффектились от изменения этих пределов. Думаю это надо поправить.

**Comment by igor-smolkov** [comment]
> Странное поведение. При попытке назначить не валидное значение для минимального значения он сначала возвращает предыдущее минимальное значение, а потом меняется на какое-то другое. Этот баг у меня перестал воспроизводится, сейчас просто меняется значение.
> 
>  12-12-01.mp4 
> Тут поинт в том, что я не хотел то значение которое мне предлагает эвристика слайдера. Понятно что то значение которое я вводил не валидно, но логичным, с точки знения UX, как мне кажется, тут выглядит вернуть предыдущее значение и показать ошибку (последнее, наверное не обязательно - не будем усложнять)
> 
когда приступил к этому пункту, то обнаружил, что после последнего коммита поведение слайдера как на видео повторить не получается, при этом слайдер ведет себя как твои ожидания
на это повлияли изменения сделанные для предыдущего пункта

**Comment by igor-smolkov** [comment]
> И еще один момент, после любого изменения пределов, меняются и значения ползунков слайдера, даже если они не аффектились от изменения этих пределов. Думаю это надо поправить.

значения ползунков в некоторых случаях действительно меняются, потому что они всегда корректируются по шагу

https://user-images.githubusercontent.com/56838535/147408346-1458a9c0-13c4-465d-a5bd-2150f44f82de.mp4

например, смена значения с 4 на 5, при изменении минимума с 0 на 1 и шаге 4, кажется мне логичной

можно пример когда значения меняются не так как ожидается?

**Comment by mglknFSD** [comment]
> > И еще один момент, после любого изменения пределов, меняются и значения ползунков слайдера, даже если они не аффектились от изменения этих пределов. Думаю это надо поправить.
> 
> значения ползунков в некоторых случаях действительно меняются, потому что они всегда корректируются по шагу
> 
>  26-12-2021.192959.mp4 
> 
> например, смена значения с 4 на 5, при изменении минимума с 0 на 1 и шаге 4, кажется мне логичной
> 
> можно пример когда значения меняются не так как ожидается?

Тут штука в том что когда я смещаю граничные значения, даже если новое граничное значение не аффектит текущую позицию ползунков - они сбиваются в одну точку. Это, вроде, видно на видео. А хотелось бы, что бы они оставались на месте.

Я проверял эти баги на мастере - клонировал репу и запускал из консоли. Сегодня посмотрю еще.
