### ISSUE TITLE
при изменении min отключается range

### ISSUE THREAD

**Issue by Geksanit** [igor-smolkov/my-jquery-slider#6]
![2022-03-01_22h39_23](https://user-images.githubusercontent.com/31949379/156199779-fc096915-1866-42cb-9cce-7e88df99639a.gif)

**Comment by igor-smolkov** [comment]
согласен с проблемой  
но сейчас она больше не воспроизводится  
вероятно ушла в результате других правок  

https://user-images.githubusercontent.com/56838535/157208990-7728c15b-ac8a-4853-9982-c5d246d08e1f.mp4

**Comment by Geksanit** [comment]
![2022-03-12_21h43_17](https://user-images.githubusercontent.com/31949379/158022525-a7f6b3aa-8e57-473c-b925-825c9abde9ef.gif)
новая бага
